# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.lezhang.me
title: Le Zhang
email: le.zhang001@email.ucr.edu
author: Le Zhang
description: "Le's Personal Page"

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty
# Build sitemap
gems:
  - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - icon: github
    title: github
    url: https://github.com/lz100  
  - icon: envelope-o
    title: email
    url: mailto:le.zhang001@email.ucr.edu
 # - icon: linkedin
 #   title: linkedin
 #   url: https://www.linkedin.com/in/dcassol/
 # - icon: file-pdf-o
 #   title: CV
 #   url: img/CassolDanielaCV.pdf
#  - icon: website
#    title: CV Lattes
#    url: http://lattes.cnpq.br/5399100590606067
 # - icon: twitter
 #   title: twitter
 #   url: https://twitter.com/danicassol

